version: '3'
services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000" # For the Jekyll site
      - "35729:35729" # For livereload
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling
